Exam_Web/Pages/my-account/exam-online.cshtml.cs
using Exam_Web.CoreLayer.DTOs.Questions;
using Exam_Web.CoreLayer.Services.Exam;
using Exam_Web.DataLayer.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Exam_Web.Pages.my_account
{





    [BindProperties]
    public class exam_onlineModel : PageModel
    {

        private readonly IExamService _examService;


        public TestQuestionFilterDto QuestionList_Sender { get; set; }

        public long Id_Azmoon { get; set; }

        public List<List<bool>> AnswernList_Reciver { get; set; }

        public exam_onlineModel(IExamService examService)
        {

            AnswernList_Reciver = new List<List<bool>>()
            {
                new List<bool>() {false, false, false, false},
                new List<bool>() {false, false, false, false},
                new List<bool>() {false, false, false, false},
                new List<bool>() {false, false, false, false},
                new List<bool>() {false, false, false, false},
                new List<bool>() {false, false, false, false},
                new List<bool>() {false, false, false, false},
                new List<bool>() {false, false, false, false},
                new List<bool>() {false, false, false, false},
                new List<bool>() {false, false, false, false},

            };
            _examService = examService;



        }

        public void OnGet(int PageId,int IdAzmoon)
        {

            QuestionList_Sender = _examService.GetQuestionsByFilter(1,10, PageId);
            ViewData["IdAzmoon"] = 1;


        }

        public async Task<IActionResult> OnPost()
        {

           //await _examService.Import_Question_Answer_User(AnswernList_Reciver, Id_Azmoon, User.Identity.Name);
           return RedirectToPage("../Index");

        }

    }
}

Exam_Web/Pages/my-account/panel-teacher/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Exam_Web.Pages.my_account.panel_teacher
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Exam_Web/Pages/my-account/panel-teacher/azmoon.cshtml.cs
using Exam_Web.CoreLayer.Services.Exam;
using Exam_Web.DataLayer.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Exam_Web.Pages.my_account.panel_teacher
{

    [BindProperties]
    public class azmoonModel : PageModel
    {

        private readonly IExamService _examService;



        public List<Azmoon> All_Azmoon;


        public azmoonModel(IExamService examService)
        {
            _examService = examService;
        }

        public void OnGet()
        {

            All_Azmoon= _examService.GetAllAzmoons();




        }
    }
}

Exam_Web/Pages/my-account/panel-teacher/edit-azmoon.cshtml.cs
using Exam_Web.CoreLayer.Services.Exam;
using Exam_Web.DataLayer.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Exam_Web.Pages.my_account.panel_teacher
{


    [BindProperties]
    public class edit_azmoonModel : PageModel
    {


        private readonly IExamService _examService;

        
        public long? _idazmoon { get; set; }
        public List<TestQuestion>? _questions { get; set; }
        

        public edit_azmoonModel(IExamService examService)
        {
            _examService = examService;
        }


        
        public void OnGet()
        {
            var idazmoon = 2;
            _idazmoon = idazmoon;

        _questions = _examService.GetQuestionsByAzmoon(idazmoon);
        

        }
      
        public IActionResult OnGetDeletetest(int id)
        {
            
            throw new Exception("sdada");
            RedirectToPage();
        }
    }

    
}

Exam_Web/Pages/my-account/panel-teacher/azmoon.cshtml
@page
@model Exam_Web.Pages.my_account.panel_teacher.azmoonModel
@{
}














<div class="container">
    <div class="row">
        <div class="col-auto"></div>
    </div>
</div>









        <div class="container">
            <div class="row">
                
            @{
                foreach (var azmoon in @Model.All_Azmoon)
                {

                    <div class="col-auto">
                        <div class="card" style="width: 18rem;">
                            <div class="card-body">
                                <h5 class="card-title">@azmoon.Title</h5>
                                
                                <a asp-page="../exam-online" asp-route-idazmoon="@azmoon.AzmoonId"  class="btn btn-primary">شروع آزمون</a>
                            </div>
                        </div>


                    </div>
                }
            }
                
                </div>
        </div>

Exam_Web/Pages/my-account/panel-teacher/edit-azmoon.cshtml
@page 
@model Exam_Web.Pages.my_account.panel_teacher.edit_azmoonModel
@{
}



<div class="container">
    <div class="row">
              
        @{
            foreach (var question in @Model._questions)
            {

                <div class="col-12">
                    <div class="card" style="width: 18rem;">
                        <div class="card-body">
                            <h5 class="card-title">@question.Question</h5>
                            <p>@question.Gozine1</p>   
                            <br/>
                            <p>@question.Gozine2</p>   
                            <br/>
                            <p>@question.Gozine3</p>   
                            <br/>
                            <p>@question.Gozine4</p>   
                            <br/>
                          
                        </div>
                    </div>


                </div>

              <a asp-page-handler="deletetest" asp-route-id="2">fff</a>

            }
        }
                
        
        
        

    </div>
</div>