Exam_Web/Pages/Login/Index.cshtml.cs
using Exam_Web.CoreLayer.DTOs.Users;
using Exam_Web.CoreLayer.Services.Users;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;

namespace Exam_Web.Pages.Login
{




    [BindProperties]
    public class IndexModel : PageModel
    {

        private readonly IUserService _userService;

        public IndexModel(IUserService userService)
        {
            _userService = userService;
        }



        [Display(Name = "نام کاربری")]
        [Required(ErrorMessage = "{0} را وارد کنید")]
        public string UserName { get; set; }

        [Display(Name = "کلمه عبور")]
        [Required(ErrorMessage = "{0} را وارد کنید")]
        [MinLength(6, ErrorMessage = "{0} باید بیشتر از 5 کاراکتر باشد")]
        public string Password { get; set; }



        public void OnGet()
        {
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid == false)
            {
                return Page();
            }

            var user = _userService.LoginUser(new LoginUserDto()
            {
                UserName = UserName,
                Password = Password
            });


            if (user == null)
            {
 //               ModelState.AddModelError("UserName", "کاربری با مشخصات وارد شده یافت نشد");
                  return Page();
            }

            return RedirectToPage("../Index");

        }
    }
}

Exam_Web/Pages/account/login.cshtml.cs
using Exam_Web.CoreLayer.DTOs.Users;
using Exam_Web.CoreLayer.Services.Users;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;
using Exam_Web.DataLayer.Entities;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;

namespace Exam_Web.Pages.account
{

    [BindProperties]
    public class loginModel : PageModel
    {
        private readonly IUserService _userService;
        
        public loginModel(IUserService userService)
        {
            _userService = userService;
            
        }



        [Display(Name = "نام کاربری")]
        [Required(ErrorMessage = "{0} را وارد کنید")]
        [StringLength(30, ErrorMessage = "طول {0} باید بین {2} و {1} باشد", MinimumLength = 6)]
        public string UserName { get; set; }

        [Display(Name = "کلمه عبور")]
        [Required(ErrorMessage = "{0} را وارد کنید")]
        [StringLength(30, ErrorMessage = "طول {0} باید بین {2} و {1} باشد", MinimumLength = 8)]
        public string Password { get; set; }

        [Display(Name = "یادآوری کلمه عبور")]
        public bool RememberMe { get; set; }







        public string ReturnUrl { get; set; }
        public IList<AuthenticationScheme> ExternalLogins { get; set; }









        public async Task OnGet()
        {


            ReturnUrl = "%2F";
            ExternalLogins = (await _userService.GetExternalAuthenticationSchemesAsync()).ToList();
            

            ViewData["returnUrl"] = ReturnUrl;
            

        }

        public async Task<IActionResult> OnPost()
        {
            
                

            if (ModelState.IsValid)
            {
                var result = await _userService.LoginUser(new LoginUserDto()
                {
                    UserName = UserName,
                    Password = Password,
                    RememberMe = RememberMe
                });

                if (!result.Succeeded)
                {
                    if (result.IsLockedOut)
                    {
                        ModelState.AddModelError("UserName", "اکانت شما تا اطلاع ثانوی قفل شده است");
                        return Page();
                    }
                    else
                    {
                        ModelState.AddModelError("UserName", "نام کاربری یا رمز عبور اشتباه هست");
                        return Page();
                    }
                   
                }
                else
                {
                    return RedirectToPage("../Index");
                }

            }
            else
            {
                return Page();
            }


            return RedirectToPage("../Index");
        }

        private DateTime GetExpireDateTime(bool isRememberMe)
        {
            return isRememberMe ? DateTime.UtcNow.AddDays(30) : DateTime.UtcNow.AddDays(1);
        }

        
        public IActionResult OnPostExternalLogin(string provider, string returnUrl)
        {
            var redirectUrl = "https://localhost:7271/account/login/?handler=ExternalLoginCallBack";



            var properties = _userService.ConfigureExternalAuthenticationProperties(provider, redirectUrl);
            return new ChallengeResult(provider, properties);
        }

        public async Task<IActionResult> OnGetExternalLoginCallBack(string returnUrl = null, string remoteError = null)
        {
            returnUrl =
                (returnUrl != null && Url.IsLocalUrl(returnUrl)) ? returnUrl : Url.Content("~/");


            ReturnUrl = returnUrl;
                ExternalLogins = (await _userService.GetExternalAuthenticationSchemesAsync()).ToList();
            

            if (remoteError != null)
            {
                ModelState.AddModelError("", $"Error : {remoteError}");
                return Page();
            }

            var externalLoginInfo = await _userService.GetExternalLoginInfoAsync();
            if (externalLoginInfo == null)
            {
                ModelState.AddModelError("ErrorLoadingExternalLoginInfo", $"مشکلی پیش آمد");
                return Page();
            }

            var signInResult = await _userService.ExternalLoginSignInAsync(externalLoginInfo.LoginProvider,
                externalLoginInfo.ProviderKey, false, true);

            if (signInResult.Succeeded)
            {
                return RedirectToPage("Login", "ExternalLoginCallBack");
            }

            var email = externalLoginInfo.Principal.FindFirstValue(ClaimTypes.Email);

            if (email != null)
            {
                var user = await _userService.FindByEmailAsync(email);
                if (user == null)
                {
                    var userName = email.Split('@')[0];
                    user = new UserIdentity()
                    {
                        UserName = (userName.Length <= 10 ? userName : userName.Substring(0, 10)),
                        Email = email,
                        EmailConfirmed = true
                    };

                    await _userService.CreateUserAsync(user);
                }

                await _userService.AddLoginAsync(user, externalLoginInfo);
                await _userService.SignInAsync(user, false);

                return Redirect(returnUrl);
            }

            return Page();
        }
    }



}

Exam_Web/Pages/account/register.cshtml.cs
using Exam_Web.CoreLayer.DTOs.Users;
using Exam_Web.CoreLayer.Services.Users;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authentication;

namespace Exam_Web.Pages.account
{


    [BindProperties]
    public class registerModel : PageModel
    {
        private readonly IUserService _userService;



        #region Properties

        [Display(Name = "نام کاربری")]
        [Required(ErrorMessage = "{0} را وارد کنید")]
        [StringLength(30, ErrorMessage = "طول {0} باید بین {2} و {1} باشد", MinimumLength = 6)]
        [PageRemote(PageHandler = "IsUserNameInUse", HttpMethod = "Get")]
        public string UserName { get; set; }

        [Display(Name = "ایمیل")]
        [Required(ErrorMessage = "{0} را وارد کنید")]
        [EmailAddress(ErrorMessage = "ایمیل وارد شده صحیح نیست")]
        [PageRemote(PageHandler = "IsEmailInUse", HttpMethod = "Get")]
        [StringLength(40, ErrorMessage = "طول {0} باید  حداکثر  {1} کاراکتر باشد")]
        public string Email { get; set; }

        [Display(Name = "کلمه عبور")]
        [Required(ErrorMessage = "{0} را وارد کنید")]
        [MinLength(8, ErrorMessage = "{0} باید بیشتر از 7 کاراکتر باشد")]
        [StringLength(30, ErrorMessage = "طول {0} باید بین {2} و {1} باشد", MinimumLength = 8)]
        public string Password { get; set; }





        



        #endregion



        public registerModel(IUserService userService)
        {
            _userService = userService;
        }



        public void OnGet()
        {
        }





        public async Task<IActionResult> OnPost()
        {


            if (ModelState.IsValid == false)
            {
                return Page();
            }
            var result = await _userService.RegisterUser(new RegisterUserDto()
            {
                UserName = UserName,
                Password = Password,
                Email = Email
            });



            if (!result.Succeeded)
            {
                var error_username = false;
                var error_password = false;
                var error_email = false;
                foreach (var error in result.Errors)
                {

                    if (error.Code.Contains("Password") && error_password != true)
                    {
                        error_password = true;
                        ModelState.AddModelError("Password", error.Description);
                    }
                    else if (error.Code.Contains("UserName") && error_username != true)
                    {
                        error_username = true;
                        ModelState.AddModelError("UserName", error.Description);
                    }
                    else if (error.Code.Contains("Email") && error_email != true)
                    {
                        ModelState.AddModelError("Email", error.Description);
                        error_email = true;
                    }
                    else
                    {
                        ModelState.AddModelError("UserName", error.Description);
                        error_username = true;
                    }
                    return Page();

                }



                return Page();
            }

            return RedirectToPage("../Index");

        }




        [ValidateAntiForgeryToken]
        public async Task<JsonResult> OnGetIsEmailInUse(string email)
        {
            var user = await _userService.IsEmailInUse(email);
            if (user == null) return new JsonResult(true);
            return new JsonResult("ایمیل وارد شده از قبل موجود است");
        }


        [ValidateAntiForgeryToken]
        public async Task<JsonResult> OnGetIsUserNameInUse(string userName)
        {
            var user = await _userService.IsUserNameInUse(userName);
            if (user == null)
                return new JsonResult(true);
            return new JsonResult("نام کاربری وارد شده توسط شخص دیگری انتخاب شده است");
        }





    }


}

Exam_Web/Pages/account/login.cshtml
@page
@model Exam_Web.Pages.account.loginModel
@{
}
@section MetaTags
{
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
}

@section Links
{
   <link rel="stylesheet" href="~/css/login.css">
}



<body >
     <div class="main-backgroung" style="background-color: #F8F9FD;" class="align-items-center">
  <div class="container" style="height: 100vh;">
    <div class="row justify-content-center align-items-center ">
      <div class="col-md-6 col-lg-5 col-xl-4 row-main-page row-main-page-right">
        <div class="row text_align_center mb-4">
          <h3>ورود</h3>
        </div>
        <div class="row">
            <form method="post">
                <div class="mb-2">
                    <img src="img/people.svg" alt="">
                    نام کاربری
                </div>
                <div class="row"  style="height: 72px">
                    <div class="col">
                        <input class=" form-control-lg input-form-login " type="text" placeholder="نام کاربری" asp-for="UserName">
                        <span class="text-danger " asp-validation-for="UserName"  style="font-size: 13px"></span>
                    </div>
                </div>
                <div class=" mb-2">
                    <img src="img/lock.svg" alt="">
                    رمز عبور
                </div>
                <div class="row"  style="height: 72px">
                    <div class="col">
                        <input class=" form-control-lg input-form-login " type="text" placeholder="رمز عبور" asp-for="Password">
                        <span class="text-danger " asp-validation-for="Password"  style="font-size: 13px"></span>
                    </div>
                </div>
                <button class="btn-form-login mb-3" type="submit">
                    ورود
                </button>
                <div class="row justify-content-between">
                    <div class="col-6 mb-3">
                        <div class="form-check">
                            <input class="form-check-input input-check-remember-me"  type="checkbox" id="flexCheckDefault" asp-for="RememberMe">
                            <label class="form-check-label label-remember-password" for="flexCheckDefault">
                                مرا بخاطر بسپار
                            </label>
                        </div>
                    </div>
                    <div class="col-5">
                        <a href="" class="a-forgot-password">فراموشی رمز عبور </a>
                    </div>
                </div>
                <div class="row justify-content-center login-accounts">
                    <a href="#" class="d-flex align-items-center justify-content-center login-account"><i
                                                                                                           class="fa-brands fa-facebook-f"></i></a>
                    <a href="#" class="d-flex align-items-center justify-content-center login-account"><i
                                                                                                           class="fa-brands fa-google"></i></a>
                    <a href=" #" class="d-flex align-items-center justify-content-center login-account"><i
                                                                                                            class="fa-brands fa-twitter"></i></a>
                </div>
            </form>
            
            
            @{


                /*

            <div class="row mb-3">
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <h5 class="font-medium m-b-20" style="font-size: 16px">یا ورود با استفاده از اکانت :</h5>
                @{
                    if (!Model.ExternalLogins.Any())
                    {
                        <div>در حال حاضر امکان ورود با اکانت های دیگر وجود ندارد</div>
                    }
                    else
                    {
                        <form method="post" asp-page-handler="ExternalLogin" asp-route-returnUrl="@Model.ReturnUrl">
                            <div class="social">
                                @foreach (var provider in Model.ExternalLogins)
                                {

                                    <button type="submit" value="@provider.Name"
                                            class="btn btn-primary" name="provider"
                                            title="ورود با استفاده از اکانت @provider.DisplayName ">
                                        @provider.DisplayName
                                    </button>

                                }
                            </div>
                        </form>
                    }

                }
            </div>
        </div>
        */


            }
        </div>
      </div>
      <div class="col-md-6 col-lg-5 col-xl-4 text_align_center row-main-page row-main-page-left d-none d-md-block">
        <p></p>
      </div>
    </div>

    </div>
     </div>
</body>

Exam_Web/Pages/account/register.cshtml
@page
@model Exam_Web.Pages.account.registerModel
@{
}


@section MetaTags
{
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
}

@section Links
{
    <link rel="stylesheet" href="~/css/register.css">
}









   <div class="main-backgroung" style="background-color: #F8F9FD;" class="align-items-center">
  
   <div class="container" style="height: 100vh;">
       <div class="row justify-content-center align-items-center ">
           <div class="col-md-6 col-lg-5 col-xl-4 row-main-page row-main-page-right">
               <div class="row text_align_center mb-4">
                   <h3>ثبت نام</h3>
               </div>
               <div class="row">
                   <form method="Post">
                       <div class="mb-2">
                           <img class="username-icon" alt="">
                           نام کاربری
                       </div>
                       <div class="row " style="height: 72px">
                           <div class="col">
                               <input class=" form-control-lg input-form-login " type="text" placeholder="نام کاربری"  asp-for="UserName">
                               <div class=" text-center">
                                   <span class="text-danger " asp-validation-for="UserName"  style="font-size: 13px"></span>
                               </div>
                           </div>
                       </div>
                       <div class=" mb-2">
                           <img class="password-icon" alt="">
                           رمز عبور
                       </div>
                       <div class="row "style="height: 72px">
                           <div class="col">
                               <input class=" form-control-lg input-form-login" type="text" placeholder="رمز عبور" asp-for="Password">
                               <div class=" text-center">
                                   <span class="text-danger " asp-validation-for="Password"  style="font-size: 13px"></span>
                               </div>
                           </div>
                       </div>
                       <div class="mb-2">
                           <img class="email-icon" alt="">
                           ایمیل
                       </div>
                       <div class="row "style="height: 72px">
                           <div class="col">
                               <input class=" form-control-lg input-form-login " type="text" placeholder="ایمیل" asp-for="Email">
                               <div class=" text-center">
                                   <span class="text-danger " asp-validation-for="Email"  style="font-size: 13px"></span>
                               </div>
                           </div>
                       </div>
                       <button class="btn-form-login mb-2 mt-3">
                           ثبت نام
                       </button>
                       <div class="row justify-content-center login-accounts mt-2">
               
                           <a href="#" class="d-flex align-items-center justify-content-center login-account"><i class="fa-brands fa-google"></i></a>
               
                       </div>
                   </form>
               </div>
           </div>
           <div class="col-md-6 col-lg-5 col-xl-4 text_align_center row-main-page row-main-page-left d-none d-md-block">
               <p></p>
           </div>
       </div>

    </div>